# creation rules are evaluated sequentially, the first match wins
creation_rules:
  - # only encrypt data of k8s secrets, not metadata
    unencrypted_regex: "^(apiVersion|metadata|kind|type)$"
    # argo test age key
    age: age13w29hnd6qg2t4agalgjzc8ne2me0xxk0s0lhqn7sdqvqh976efzsl2g4ff
