replicaCount: ENC[AES256_GCM,data:cw==,iv:1PWIgxK6KMwu7Xa3mNLN/7weZjeM1lnf21771Q1SKb4=,tag:0Ndkup6DF01wKA7+AMn/fQ==,type:int]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13w29hnd6qg2t4agalgjzc8ne2me0xxk0s0lhqn7sdqvqh976efzsl2g4ff
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsUktzMVQxTUljRHZxVXB6
            WEJvc2pYSzRhT0pQNm43UjVtTTk2eFhRcmdZCmpXZGxrb3UzcWFkUnhvV3dQclB4
            a1dZVjBRbC9RZjg4ZGROMmo1N3NzV2sKLS0tIHIvUFlNN2VMZDZIeW44QXR0aEtj
            VUlwSjljWWpuM24wZE9CUXZVSmpTckkKQl6A1wwCwm+ryqeDRyNz8kIdcemYU0/B
            hJWkds4HNxkm8FBT8qSkUhCapVVu09ULCB1sHVpaZXJ4oz+z5SKg8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-26T13:00:55Z"
    mac: ENC[AES256_GCM,data:qJtwv1Wgiv6e8Qci5uYoRyfWZLydXAvYO00LgSO+Ad5KohW6DPg2QGEl6e5ceMAhJWe028w3hTwQbNJq43EYnIm+Z8IEyx+yc1KFVDWbCxThAj/DmZ6Ow7SsnELfgtcdCC25gnQ6pe+ludq96uOAsrnRHiaUxbO+jb4n/RWGnUg=,iv:+Xj1BPxP3fmylF7Dt8i8TJ1g52RnebcqqHCgPQMnmz0=,tag:Bu2/lDlbONfdZEjJHTJhgQ==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.7.3
